language: scala
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

matrix:
  include:
  - env: SBT_VERSION="0.13.18"
    jdk: openjdk11
  - env: SBT_VERSION="1.5.1"
    jdk: openjdk11
script:
- sbt "^^${SBT_VERSION}" test scripted
