name: CI
on: [push, pull_request]
jobs:
  assemble:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [1.8.282, 1.11.0, 1.17.0-0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: "zulu@${{ matrix.jdk }}"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build
        shell: bash
        run: sbt -v compile
      - name: Sbt Scripted Test
        shell: bash
        run: sbt scripted
      - name: Cleanup before cache
        shell: bash
        run: |
            rm -rf "$HOME/.ivy2/local" || true
            find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
            find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
            find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
            find $HOME/.sbt                              -name "*.lock"               -delete || true
